language: go

sudo: required

go:
- 1.10.x

before_install:
# system dependencies
- sudo apt-get install -y --force-yes libglu1-mesa-dev libgles2-mesa-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev libasound2-dev

# rename package name for imports
- mv $HOME/gopath/src/github.com/Vehsamrak $HOME/gopath/src/github.com/vehsamrak

# downloading dependencies
- go get -t -v ./...

script:
- bash <(curl -s https://raw.githubusercontent.com/vehsamrak/go-multi-package-coverage/1.0.0/test.sh)

after_success:
- bash <(curl -s https://codecov.io/bash)
